"""initial schema with private CA tables

Revision ID: 055f9904687d
Revises: 
Create Date: 2026-05-24 09:25:40.861591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055f9904687d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ca_name', sa.String(length=100), nullable=False),
    sa.Column('ca_type', sa.String(length=50), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('api_secret', sa.String(length=500), nullable=True),
    sa.Column('default_validity_days', sa.Integer(), nullable=True),
    sa.Column('auto_renewal_enabled', sa.Boolean(), nullable=True),
    sa.Column('renewal_threshold_days', sa.Integer(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ca_name')
    )
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('not_valid_before', sa.DateTime(), nullable=False),
    sa.Column('not_valid_after', sa.DateTime(), nullable=False),
    sa.Column('days_until_expiry', sa.Integer(), nullable=True),
    sa.Column('signature_algorithm', sa.String(length=100), nullable=True),
    sa.Column('certificate_type', sa.String(length=50), nullable=True),
    sa.Column('issuer_category', sa.String(length=50), nullable=True),
    sa.Column('issuer_info', sa.JSON(), nullable=True),
    sa.Column('subject_info', sa.JSON(), nullable=True),
    sa.Column('subject_alt_names', sa.JSON(), nullable=True),
    sa.Column('key_usage', sa.JSON(), nullable=True),
    sa.Column('extended_key_usage', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_scanned', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('private_cas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ca_type', sa.String(length=50), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('organizational_unit', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('locality', sa.String(length=100), nullable=True),
    sa.Column('cert_pem', sa.Text(), nullable=False),
    sa.Column('key_file_path', sa.String(length=500), nullable=True),
    sa.Column('crl_pem', sa.Text(), nullable=True),
    sa.Column('crl_last_generated', sa.DateTime(), nullable=True),
    sa.Column('crl_next_update', sa.DateTime(), nullable=True),
    sa.Column('crl_distribution_url', sa.String(length=500), nullable=True),
    sa.Column('ocsp_url', sa.String(length=500), nullable=True),
    sa.Column('validity_years', sa.Integer(), nullable=True),
    sa.Column('key_type', sa.String(length=20), nullable=True),
    sa.Column('key_size', sa.Integer(), nullable=True),
    sa.Column('path_length', sa.Integer(), nullable=True),
    sa.Column('not_valid_before', sa.DateTime(), nullable=True),
    sa.Column('not_valid_after', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['private_cas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=True),
    sa.Column('scan_path', sa.String(length=500), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=True),
    sa.Column('certificates_found', sa.Integer(), nullable=True),
    sa.Column('certificates_added', sa.Integer(), nullable=True),
    sa.Column('certificates_updated', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scan_results', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('certificate_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('owner_username', sa.String(length=100), nullable=True),
    sa.Column('owner_url', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('application_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('days_before_expiry', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privately_issued_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('cert_type', sa.String(length=50), nullable=True),
    sa.Column('cert_pem', sa.Text(), nullable=True),
    sa.Column('key_file_path', sa.String(length=500), nullable=True),
    sa.Column('subject_info', sa.JSON(), nullable=True),
    sa.Column('san_dns', sa.JSON(), nullable=True),
    sa.Column('san_ips', sa.JSON(), nullable=True),
    sa.Column('san_emails', sa.JSON(), nullable=True),
    sa.Column('key_usage', sa.JSON(), nullable=True),
    sa.Column('extended_key_usage', sa.JSON(), nullable=True),
    sa.Column('not_valid_before', sa.DateTime(), nullable=True),
    sa.Column('not_valid_after', sa.DateTime(), nullable=True),
    sa.Column('days_validity', sa.Integer(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('revocation_reason', sa.String(length=100), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ca_id'], ['private_cas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('renewal_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('ca_provider', sa.String(length=50), nullable=True),
    sa.Column('renewal_method', sa.String(length=50), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('new_certificate_path', sa.String(length=500), nullable=True),
    sa.Column('new_expiry_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('renewal_attempts')
    op.drop_table('privately_issued_certificates')
    op.drop_table('notification_logs')
    op.drop_table('certificate_ownership')
    op.drop_table('users')
    op.drop_table('scan_jobs')
    op.drop_table('private_cas')
    op.drop_table('certificates')
    op.drop_table('ca_configurations')
    # ### end Alembic commands ###
