"""add_private_ca_fk_to_ca_configurations

Revision ID: 2cdf566889b7
Revises: 055f9904687d
Create Date: 2026-05-24 09:45:16.179666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdf566889b7'
down_revision: Union[str, None] = '055f9904687d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_cas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ca_type', sa.String(length=50), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('organizational_unit', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('locality', sa.String(length=100), nullable=True),
    sa.Column('cert_pem', sa.Text(), nullable=False),
    sa.Column('key_file_path', sa.String(length=500), nullable=True),
    sa.Column('crl_pem', sa.Text(), nullable=True),
    sa.Column('crl_last_generated', sa.DateTime(), nullable=True),
    sa.Column('crl_next_update', sa.DateTime(), nullable=True),
    sa.Column('crl_distribution_url', sa.String(length=500), nullable=True),
    sa.Column('ocsp_url', sa.String(length=500), nullable=True),
    sa.Column('validity_years', sa.Integer(), nullable=True),
    sa.Column('key_type', sa.String(length=20), nullable=True),
    sa.Column('key_size', sa.Integer(), nullable=True),
    sa.Column('path_length', sa.Integer(), nullable=True),
    sa.Column('not_valid_before', sa.DateTime(), nullable=True),
    sa.Column('not_valid_after', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['private_cas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('privately_issued_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('cert_type', sa.String(length=50), nullable=True),
    sa.Column('cert_pem', sa.Text(), nullable=True),
    sa.Column('key_file_path', sa.String(length=500), nullable=True),
    sa.Column('subject_info', sa.JSON(), nullable=True),
    sa.Column('san_dns', sa.JSON(), nullable=True),
    sa.Column('san_ips', sa.JSON(), nullable=True),
    sa.Column('san_emails', sa.JSON(), nullable=True),
    sa.Column('key_usage', sa.JSON(), nullable=True),
    sa.Column('extended_key_usage', sa.JSON(), nullable=True),
    sa.Column('not_valid_before', sa.DateTime(), nullable=True),
    sa.Column('not_valid_after', sa.DateTime(), nullable=True),
    sa.Column('days_validity', sa.Integer(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('revocation_reason', sa.String(length=100), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ca_id'], ['private_cas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('ca_configurations', sa.Column('private_ca_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ca_configurations', 'private_cas', ['private_ca_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ca_configurations', type_='foreignkey')
    op.drop_column('ca_configurations', 'private_ca_id')
    op.drop_table('privately_issued_certificates')
    op.drop_table('private_cas')
    # ### end Alembic commands ###
